### PR TITLE
Prefer partial success to failure

### LINKED ISSUE #124: ”Permission denied“ since v0.7.1
I found this when we upgraded https://github.com/seanmonstar/reqwest/issues/2391, one of our users reported this, https://github.com/rustdesk/rustdesk-server-pro/issues/360. It is not easy to reproduce, I can only see this on his machine so far.
```
❯ ./test-master
Custom { kind: PermissionDenied, error: "could not load certs from dir /usr/lib/ssl/certs: Permission denied (os error 13)" }
❯ ./test-v0.6.2
ok
❯ ./test-v0.6.3
ok
❯ ./test-v0.7.0
ok
❯ ./test-v0.7.1
Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

❯ sudo ./test-master
ok
❯ sudo ./test-v0.6.2
ok
❯ sudo ./test-v0.6.3
ok
❯ sudo ./test-v0.7.0
ok
❯ sudo ./test-v0.7.1
ok
```

The test is
```
use std::error::Error;
use x509_parser::prelude::*;

fn main() -> Result<(), Box<dyn Error>> {
    if let Err(err) = rustls_native_certs::load_native_certs() {
      println!("{:?}", err);
    }
    Ok(())
}
```

### PR DESCRIPTION
**Pull request by ctz**
fixes #124 

Draft release notes:

* If loading certificates from a directory fails, only raise that error if no certificates were successfully loaded from a file. See #124.
  
  In 0.8.0 we plan to alter the API to give the caller full error details, so they can choose the level of success they require; see #128.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -157,18 +157,33 @@ impl CertPaths {
...
+            match load_pem_certs_from_dir(cert_dir)
+                .map_err(|err| Self::load_err(cert_dir, "dir", err))
+            {
+                Ok(mut from_dir) => certs.append(&mut from_dir),
+                Err(err) => first_error = first_error.or(Some(err)),
+            }
+        }
+
+        // promote first error if we have no certs to return
+        if let (Some(error), []) = (first_error, certs.as_slice()) {
```
Comment (djc) [inline src/lib.rs:191]: Just to call this out: is the 0 vs 1 boundary the right one? It is different from the previous approach -- it would be "more" backwards-compatible if we just swallowed the error from `load_pem_certs_from_dir()`, I suppose?

File: src/lib.rs [hunk 2]
```diff
@@ -165,6 +165,8 @@ impl CertPaths {
             {
                 Ok(certs) => certs,
                 Err(err) => {
+                    #[cfg(feature = "tracing")]
+                    tracing::error!("error loading certs: {:?}", err);
```
Comment (djc) [inline src/lib.rs:169]: "from file"?

File: src/lib.rs [hunk 3]
```diff
@@ -177,7 +179,11 @@ impl CertPaths {
                 .map_err(|err| Self::load_err(cert_dir, "dir", err))
             {
                 Ok(mut from_dir) => certs.append(&mut from_dir),
-                Err(err) => first_error = first_error.or(Some(err)),
+                Err(err) => {
+                    #[cfg(feature = "tracing")]
+                    tracing::error!("error loading certs: {:?}", err);
```
Comment (djc) [inline src/lib.rs:184]: "from dir"?

**Review by djc — COMMENTED** [review]
If we're going to do this, should we also try to be more forgiving inside `load_certs_from_dir()`? What about the various implementations of `load_certs()`? I think both could skip over some error cases.

Are we trying to maintain backwards compatibility or making the library entirely best effort? And if it's the latter, wouldn't it still be better to make the API explicit about this by returning retrieved certificates and errors so that the application can decide how strict it wants to be?

**Review by cpu — APPROVED** [review]
Thanks, this seems reasonable to me.

**Comment by cpu** [comment]
> If we're going to do this, should we also try to be more forgiving inside load_certs_from_dir()? What about the various implementations of load_certs()? I think both could skip over some error cases.

I'm not sure I follow what you're thinking here, the only public API surface is `load_native_certs()`, which calls the crate internal `load()` being updated in this changeset. I don't think there's anywhere else that needs to be updated to skip error cases :thinking:

File: src/lib.rs (hunk 2 above)
Comment (ctz) [reply src/lib.rs:169]: this is actually already decorated into the underlying error. sample output:

```
2024-08-27T09:10:37.040117Z ERROR rustls_native_certs: error loading certs: Custom { kind: NotADirectory, error: "could not load certs from dir /dev/null: Not a directory (os error 20)" }
```

**Comment by ctz** [comment]
So if we follow https://github.com/rustls/rustls-native-certs/pull/128#issuecomment-2312763490, which I think we should, I am minded to remove the tracing stuff here (the feature, dependency, and calls), on the basis that:

- even though the new API is a breaking change, adding and then immediately removing a feature & dependency seems a bit silly
- the new API fixes this in a more convincing way, so the half-assed way of logging swallowed errors is a cul-de-sac

**Comment by cpu** [comment]
> So if we follow https://github.com/rustls/rustls-native-certs/pull/128#issuecomment-2312763490, which I think we should, I am minded to remove the tracing stuff here (the feature, dependency, and calls)

That sounds sensible to me 👍

**Comment by djc** [comment]
Yup, makes sense.

**Comment by ctz** [comment]
Dropped that commit.

**Comment by ctz** [comment]
Added up top, please review.

**Comment by cpu** [comment]
LGTM too, thanks!
